name: hello-world
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter the name in the box'
        type: string
        required: true
        
jobs:
  my-job:
    
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          if [[ "${{inputs.environment}}" != "vinay" ]]; then
            echo "Hello ${{ inputs.environment }}"
          else 
             echo "Hello ${{ inputs.environment }}"  
          fi
          exit 0

        shell: bash
