name: hello-world
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter the name in the box'
        type: string
        required: true
        
jobs:
  my-job:
    runs-on: ubuntu-latest
    if: ${{ inputs.name }} != 'vinay'
    steps:
      - name: my-step
        run: echo "Hello ${{ inputs.name }}"
        
  my-job1:
    runs-on: ubuntu-latest
    if: ${{ inputs.name }} == 'vinay'
    steps:
      - name: my-step
        run: echo "Hello ${{ inputs.name }}"   
